[build]
  publish = "."

[[redirects]]
  from   = "/menu/*"
  to     = "https://mybar-2fla.onrender.com/menu/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/sira-degistir"
  to     = "https://mybar-2fla.onrender.com/sira-degistir"
  status = 200
  force  = true

[[redirects]]
  from   = "/admin"
  to     = "/admin/index.html"
  status = 200

[[redirects]]
  from   = "/user"
  to     = "/user/index.html"
  status = 200
