[build]
  publish = "."

# Sadece “tam olarak” /admin veya /admin/ URL’lerini index’e yönlendir:
[[redirects]]
  from   = "/admin"
  to     = "/admin/index.html"
  status = 200
  force  = true

[[redirects]]
  from   = "/admin/"
  to     = "/admin/index.html"
  status = 200
  force  = true

# Login proxy
[[redirects]]
  from   = "/login"
  to     = "https://mybar-2fla.onrender.com/login"
  status = 200
  force  = true

# Menü proxy
[[redirects]]
  from   = "/menu/*"
  to     = "https://mybar-2fla.onrender.com/menu/:splat"
  status = 200
  force  = true

# Sıra değiştir proxy
[[redirects]]
  from   = "/sira-degistir"
  to     = "https://mybar-2fla.onrender.com/sira-degistir"
  status = 200
  force  = true
